const language=require('../routes/language')
const bodyParser = require('body-parser')
const customer = require('../routes/customer')
const project = require('../routes/project')
const pay_plan = require('../routes/pay_plan')
const state = require('../routes/state')
const technology =require('../routes/technology')
const role =require('../routes/role')
const employee_language =require('../routes/employee_language')
const employee_project =require('../routes/employee_project')
const employee_technology =require('../routes/employee_technology')
const employee =require('../routes/employee')
const offer = require('../routes/offer')
const auth = require('../routes/auth')
module.exports=function(app){
    app.use(bodyParser.json())
    app.use(bodyParser.urlencoded({extended:true}))
    app.use('/api/languages',language)
    app.use('/api',customer)
    app.use('/api',project)
    app.use('/api',pay_plan)
    app.use('/api',state)
    app.use('/api/employees_projects',employee_project)
    app.use('/api/employees_languages',employee_language)
    app.use('/api/employees_technologies',employee_technology)
    app.use('/api/employees',employee)
    app.use('/api/roles',role)
    app.use('/api/technologies',technology)
    app.use('/api',offer)
    app.use('/api',auth)
}